# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage : 'Build' 
  displayName:  'Génération et exécution des tests'
  jobs:
    - job : 'Build'
      steps:
      - script: echo build

- stage : 'DeployToDev' 
  displayName:  'Déploiment en Dev'
  dependsOn: 'Build'
  jobs:
    - deployment : 'DeployToDev'
      environment: 'dev'
      strategy:
        runOnce:
         deploy:
           steps:
             - script: echo Dev

- stage : 'DeployToProd' 
  displayName:  'Déploiment en production'
  dependsOn: 'DeployToDev'
  jobs:
    - deployment : 'DeployToProd'
      environment: 'dev'
      strategy:
        runOnce:
         deploy:
           steps:
             - script: echo Prod